### ISSUE TITLE
t.item is undefined

### ISSUE THREAD

**Issue by onny** [skjnldsv/vueexample#333]
Hey,
I'm getting following error while starting vueexample:
```
[Vue warn]: Error in render: "TypeError: t.item is undefined"
```
Also the page looks messy, not sure if this is intenioned:
![2020-02-01-112933_grim](https://user-images.githubusercontent.com/757752/73590739-3f192200-44e6-11ea-9561-791d6307afbc.png)

Using Nextcloud 18.
Best regards
Jonas

**Comment by onny** [comment]
Also doesn't work for me with fresh installed Nextcloud 17 on Docker:
```
docker run -v /home/onny/projects/vueexample:/opt/nextcloud/apps/vueexample -d --name nextcloud -p 80:80 rootlogin/nextcloud
```
Same error in web console :(

**Comment by skjnldsv** [comment]
Should be fixed on latest master :)
