### ISSUE TITLE
Vue devtools

### ISSUE THREAD

**Issue by JesperBllnbm** [skjnldsv/vueexample#474]
Hi there,

I try to familiarise myself a bit with Vue development in the Nextcloud environment. It would be great to be able to use the vue dev tools to do this. Unfortunately, I always get that prompt:

```
Vue.js is detected on this page.
Devtools inspection is not available because it's in production mode or explicitly disabled by the author.
```

How can I enable them?

Thanks and KR,

**Comment by skjnldsv** [comment]
You can if you build the development build. Not the production
It only works on Chromium based browsers though, firefox have some limitations with nextcloud and csp

**Comment by JesperBllnbm** [comment]
Hi,

thanks for the super fast reply!

Can you elaborate how to build in development mode? I added:

`Vue.config.devtools = true
Vue.config.devtools = process.env.NODE_ENV === 'development'`

in the main.js. According to the console I am running a dev build:

`You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html`

I also applied the fixes for Firefox and tried to run it there but had no luck as well. 

Thanks and KR,

**Comment by skjnldsv** [comment]
https://github.com/skjnldsv/vueexample/blob/a3ab549ac33777b2141ded1eb795d16db9bdda31/package.json#L27

`npm run build` =>  production
`npm run dev` =>  development
`npm run watch` =>  development and keep watching for changes

**Comment by JesperBllnbm** [comment]
Hi, 

again thanks for the fast reply. 
I used npm run watch the problem still exists.

KR

**Comment by skjnldsv** [comment]
Again, doesn't work in firefox. Please use ahcormium.
I use docker as well, and it works, so shouldn't be an issue :)

Close/open the dev tools and/or refresh the page, sometimes it takes some time to catch the vue app.

**Comment by JesperBllnbm** [comment]
Okay, I "figured it out". There was no problem in the first place. Despite the message that the devtools are not available it actually works if I just open the tab with the devtools...

<img width="502" alt="image" src="https://user-images.githubusercontent.com/31738080/97850567-8130f780-1cf4-11eb-9e23-c4af569e7716.png">

It even works in Firefox with the fix mentioned [here](https://github.com/nextcloud/nextcloud-vue)

Thanks for your endurance!

**Comment by skjnldsv** [comment]
Nice! Have fun!! :)
Have a great day!
